# fly.toml app configuration file generated for fakev-status on 2025-01-01T01:48:19Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fakev-status'
primary_region = 'sin'

[build]

[[mounts]]
  source = 'nz_data'
  destination = '/dashboard/data'

[http_service]
  internal_port = 8008
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.http_options]
    h2_backend = true

[[vm]]
  size = 'shared-cpu-1x'
